name: KitaDojo
favicon: null
layout_spectrum: 0.083631546003744
typography_spectrum: 0.07673925906419754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.22848241170868278
  lightness: 0.8509510632138699
  saturation: 0.2334775421768427
  rhythmicContrast: 0.5210321871563792
purpose: []
